version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 9877:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  web:
    build:
      context: .
      dockerfile: Dockerfile_django
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - ${DJANGO_PORT}:8000
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEFAULT_PG_USER: ${DEFAULT_PG_USER}
      DEFAULT_PG_DB: ${DEFAULT_PG_DB}
      DEFAULT_PG_PASSWORD: ${DEFAULT_PG_PASSWORD}
    depends_on:
      - db

volumes:
  postgres_data: