# Pull base image
FROM python:3.7-slim-stretch

ARG PROJECT_DIR=.
ARG PROJECT_NAME
ARG MEDIA_PATH
ARG STATIC_PATH
ARG SOCKETS_PATH
ARG PROJECT_ROOT=$PROJECT_DIR/$PROJECT_NAME
ARG ROOT_CODE=$PROJECT_ROOT/src
ARG REQUIREMENTS=$PROJECT_ROOT/etc/

# Set work directory
WORKDIR /code

# Install system libraries
RUN apt-get update \
	&& apt-get install -y \
		python3-dev \
		build-essential \
		libpq-dev

# Install dependencies
RUN pip install --upgrade pip
RUN pip install uwsgi
ADD $REQUIREMENTS /code/
RUN pip install -r requirements.txt

# Copy project
ADD $ROOT_CODE /code/
RUN mkdir -p $MEDIA_PATH $STATIC_PATH $SOCKETS_PATH
