# Pull base image
FROM python:3.7-slim-stretch

ARG PROJECT_DIR=.
ARG PROJECT_NAME
ARG PROJECT_ROOT=$PROJECT_DIR/$PROJECT_NAME
ARG ROOT_CODE=$PROJECT_ROOT/src
ARG REQUIREMENTS=$PROJECT_ROOT/etc/

# Set work directory
WORKDIR /code

# Install system libraries
RUN apt-get update \
	&& apt-get install -y \
		python3-dev \
		libpq-dev \
		libpangocairo-1.0-0 \
		libpango-1.0-0 \
		libcairo2* \
		fonts-font-awesome \
		libffi-dev \
		libgdk-pixbuf2.0-0 \
		python-lxml \
		shared-mime-info \
		libffi-dev \
		libjpeg-turbo-progs \
		zlib1g-dev \
		libfreetype6-dev \
		liblcms2-dev \
		libwebp-dev \
		tcl8.6-dev \
		tk8.6-dev \
		libharfbuzz-dev \
		libfribidi-dev

# Install dependencies
RUN pip install --upgrade pip
ADD $REQUIREMENTS /code/
RUN pip install -r requirements.txt

# Copy project
ADD $ROOT_CODE /code/
