version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 9877:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build:
      context: .
      dockerfile: Dockerfile_django
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    command: uwsgi --socket 0.0.0.0:3031 --uid root --module settings.wsgi
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEFAULT_PG_USER: ${DEFAULT_PG_USER}
      DEFAULT_PG_DB: ${DEFAULT_PG_DB}
      DEFAULT_PG_PASSWORD: ${DEFAULT_PG_PASSWORD}
    depends_on:
      - db
  server:
    image: nginx
    restart: always
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
    environment:
      NGINX_PORT: 80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 8000:80
    depends_on:
      - app
volumes:
  postgres_data: