version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile_postgres
      args:
        - PROJECT_NAME=${PROJECT_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 9877:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  app:
    build:
      context: .
      dockerfile: Dockerfile_django
      args:
        - PROJECT_NAME=${PROJECT_NAME}
        - MEDIA_PATH=${MEDIA_PATH}
        - STATIC_PATH=${STATIC_PATH}
        - SOCKETS_PATH=${SOCKETS_PATH}
    command: uwsgi --socket ${SOCKETS_PATH}/${PROJECT_NAME}.sock --module ${UWSGI_PARENT_MODULE_NAME}.wsgi --uid ${UID_FOR_SOCKETS} --gid ${GID_FOR_SOCKETS}
    restart: always
    volumes:
      - data_for_serve:${SERVER_DATA}
    environment:
      DEFAULT_DB: postgres://${DEFAULT_PG_USER}:${DEFAULT_PG_PASSWORD}@db/${DEFAULT_PG_DB}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      SECRET_KEY: ${SECRET_KEY}
      STATIC_ROOT: ${STATIC_PATH}
      LANGUAGE_CODE: ${LANGUAGE_CODE}
      TIME_ZONE: ${TIME_ZONE}
      USE_I18N: ${USE_I18N}
      USE_L10N: ${USE_L10N}
      USE_TZ: ${USE_TZ}
    depends_on:
      - db
  server:
    image: nginx
    restart: always
    volumes:
      - data_for_serve:${SERVER_DATA}
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./nginx_conf.template:/etc/nginx/nginx_conf.template
    environment:
      USER: ${UID_FOR_SOCKETS}
      NGINX_INTERNAL_PORT: ${NGINX_INTERNAL_PORT}
      SOCKETS_PATH: ${SOCKETS_PATH}
      MEDIA_PATH: ${MEDIA_PATH}
      STATIC_PATH: ${STATIC_PATH}
      PROJECT_NAME: ${PROJECT_NAME}
      DOLLAR: $$
    command: /bin/bash -c "((envsubst < /etc/nginx/nginx_conf.template > /etc/nginx/nginx.conf) && (envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf)) && exec nginx -g 'daemon off;'"
    ports:
      - ${NGINX_OUT_PORT}:${NGINX_INTERNAL_PORT}
    depends_on:
      - app

volumes:
  postgres_data:
  data_for_serve:
